### PR TITLE
Avoid use of seticon binary

### PR DESCRIPTION
**Pull request by craig65535**
This replaces the call out to `seticon` with a Cocoa lib call. With this change, users don't need to run this un-signed, compiled binary, and we can keep it out of this repository.

The Cocoa lib call is from https://apple.stackexchange.com/a/161984/28668

### CODE REVIEW

**Review by lgarron — CHANGES_REQUESTED** [review]
Thanks! This is a nice idea. :-D

Could I ask you to keep the `seticon` call as a fallback, though?
Apple is not exactly known for API stability, and I've tried to keep `folderify` as backwards- and forwards-compatible as possible. Whatever the implementation of `seticon` uses has worked for a long time, so it's the most stable approach I know.

(I tried having a look through https://github.com/sveinbjornt/osxiconutils/blob/d3b43f1dd5e1e8ff60d2dbb4df4e872388d2cd10/IconFamily/IconFamily.m but that didn't really help me.)

With that, I'd be happy to merge!

**Comment by lgarron** [comment]
> With that, I'd be happy to merge!

Also, it seems CI is a little unhappy with this — it seems the `Cocoa` library is not available by default. I could use help with that.

**Comment by craig65535** [comment]
Hello @lgarron,

> Also, it seems CI is a little unhappy with this — it seems the `Cocoa` library is not available by default. I could use help with that.

`Cocoa` is a part of PyObjC, which is bundled with the system Python 2.7 (at **/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/Cocoa**). CI must not be using the system Python 2.7?

It looks like Apple's build of Python3 (the one bundled with Xcode) does not contain PyObjC. I have to admit I never tried that version.

> Whatever the implementation of seticon uses has worked for a long time, so it's the most stable approach I know.

`seticon` uses some deprecated APIs like [AddResouce](https://developer.apple.com/documentation/coreservices/1529276-addresource?language=objc).

I think I'll have to find another way to do this. I looked into writing a Perl script, but PerlObjCBridge doesn't interface with AopKit (where the "modern" functions I need are). One way to do this might be to shell out to `Rez`/`DeRez`/`SetFile`, which use the same API calls as `seticon` (and are also deprecated).

**Comment by craig65535** [comment]
Another alternative is you could make folderify depend on PyObjC explicitly? This would allow the typical user with macOS-bundled Python 2.7 to run the utility without installing PyObjC; those running Python3 or their own Python build would need to install a dependency with `pip`. Just an idea.

**Pull request closed without merging**
